# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/exercise_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 269)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.expression = QtWidgets.QLabel(Form)
        self.expression.setObjectName("expression")
        self.verticalLayout.addWidget(self.expression)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.intenger_label = QtWidgets.QLabel(self.groupBox)
        self.intenger_label.setObjectName("intenger_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.intenger_label)
        self.intenger_input = QtWidgets.QSpinBox(self.groupBox)
        self.intenger_input.setObjectName("intenger_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.intenger_input)
        self.numerator_input = QtWidgets.QSpinBox(self.groupBox)
        self.numerator_input.setObjectName("numerator_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numerator_input)
        self.denominator_input = QtWidgets.QSpinBox(self.groupBox)
        self.denominator_input.setProperty("value", 1)
        self.denominator_input.setObjectName("denominator_input")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.denominator_input)
        self.numerator_label = QtWidgets.QLabel(self.groupBox)
        self.numerator_label.setObjectName("numerator_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.numerator_label)
        self.denominator_label = QtWidgets.QLabel(self.groupBox)
        self.denominator_label.setObjectName("denominator_label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.denominator_label)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.try_again_btn = QtWidgets.QPushButton(Form)
        self.try_again_btn.setObjectName("try_again_btn")
        self.horizontalLayout.addWidget(self.try_again_btn)
        self.check_btn = QtWidgets.QPushButton(Form)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout.addWidget(self.check_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Частина"))
        self.expression.setText(_translate("Form", "Вираз"))
        self.groupBox.setTitle(_translate("Form", "Відповідь"))
        self.intenger_label.setText(_translate("Form", "Ціле:"))
        self.numerator_label.setText(_translate("Form", "Чисельник:"))
        self.denominator_label.setText(_translate("Form", "Знаменник:"))
        self.exit_btn.setText(_translate("Form", "Вийти"))
        self.try_again_btn.setText(_translate("Form", "Пройти ще раз"))
        self.check_btn.setText(_translate("Form", "Перевірити"))
